version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data

  backend:
    build: ./has_backend
    command: gunicorn has.wsgi --bind 0.0.0.0:8000
    volumes: 
      - backend:/backend
      - static_files:/var/www
    expose:
      - 8000
    depends_on:
      - db
  
  frontend:
    build: 
      context: ./has_frontend
      dockerfile: Dockerfile.prod
    volumes: 
      - static_files:/var/www
    ports:
      - "3000:3000"
  
  nginx:
    image: nginx
    container_name: production_nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_files:/var/www
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - db

volumes:
  postgres_data:
  static_files:
  backend:
