version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data

  backend:
    build: ./has_backend
    command: gunicorn has.wsgi:application --bind 0.0.0.0:8000
    volumes: 
      - type: volume
        source: backend
        target: /backend
    expose:
      - 8000
    depends_on:
      - db

  # frontend:
  #   build: ./has_frontend
  #   command: npm start
  #   volumes: 
  #     - type: volume
  #       source: static_files
  #       target: /var/www/has/build
  #   ports:
  #     - "3000:3000"

  nginx:
    image: nginx
    volumes:
      - static_files:/var/www/has
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"


volumes:
  postgres_data:
  static_files:
  backend:

#   main_network:
#     driver:
#       bridge