version: '3.3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgressql/data

  backend:
    build: 
      context: ./has_backend
      dockerfile: Dockerfile.prod
    command: gunicorn has.wsgi --bind 0.0.0.0:8000
    volumes: 
      - static_files:/var/www/django-static
      - cctv_images:/var/www/django-static/cctv_images
      - /usr/local/cuda/lib64:/usr/local/nvidia/lib64
      - /usr/lib/x86_64-linux-gnu:/usr/local/nvidia/lib
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./config/backend/backend-production.env
  
  frontend:
    build: 
      context: ./has_frontend
      dockerfile: Dockerfile.prod
    command: serve -s build -l 4000
    expose:
      - 4000
    env_file:
      - ./config/frontend/frontend-production.env
          
  nginx:
    image: nginx
    container_name: production_nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_files:/var/www/django-static
      - cctv_images:/var/www/django-static/cctv_images
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - db

volumes:
  postgres_data:
  static_files:
  cctv_images:
  backend:
  frontend:
