version: '3.3'

services:
  db:
    image: postgres
    container_name: database_container
    volumes:
      - postgres_data:/var/lib/postgressql/data

  backend:
    build: ./has_backend
    container_name: backend_container
    command: gunicorn has.wsgi --bind 0.0.0.0:8000
    volumes: 
      - type: volume
        source: backend
        target: /backend
    expose:
      - 8000
    depends_on:
      - db
      - nginx
    networks:
      - main_network
  
  # frontend:
  #   build: ./has_frontend
  #   command: npm start
  #   volumes: 
  #     - type: volume
  #       source: static_files
  #       target: /var/www/has/build
  #   ports:
  #     - "3000:3000"

  
  nginx:
    image: nginx
    container_name: nginx_container
    volumes:
      - static_files:/var/www/has
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      - main_network

volumes:
  postgres_data:
  static_files:
  backend:

networks:
  main_network:
    driver:
      bridge