apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: has
      tier: backend
  replicas: 1
  template:
    metadata:
      labels: 
        app: has
        tier: backend
    spec:
      containers:
        - name: backend-pod
          image: samuellabrador/has_backend:latest
          ports:
            - containerPort: 8000