apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: has
      tier: backend
  replicas: 3
  template:
    metadata:
      labels: 
        app: has
        tier: backend
    spec:
      containers:
        - name: backend-pod
          image: samuellabrador/has_backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: HAS_PRODUCTION
              value: '1'
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: DB_HOST
          
          
